[package]
name = "transport_api"
version = "0.0.1"
description = "Tokio API for managing low-level transport bindings and connections"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
futures = "0.3"
thiserror = "1"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
rpc_channel = { version = "0.0.1", path = "../rpc_channel" }
url2 = "0.0.5"
