[package]
name = "skunkworx_holochain"
version = "0.0.1"
description = "holochain skunkworx"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
crossbeam-channel = "0.4.0"
skunkworx_core = { path = "../core"}
skunkworx_conductor_lib = { path = "../conductor_lib"}

[[bin]]
path = "src/main.rs"
name = "holochain-skunkworx"