[package]
name = "sx_zome_types"
version = "0.0.1"
description = "Holochain zome types"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
holochain_serialized_bytes = "=0.0.36"
serde = { version = "1.0.104", features = ["derive"] }

# TODO: remove these two dependencies and replace with HoloHash
multihash = "0.8.0"
rust-base58 = "0.0.4"

# TODO: is there a way to avoid this nicely and keep fixed size arrays?
# https://github.com/serde-rs/serde/issues/631#issuecomment-445566498
serde-big-array = "0.2.0"
