[package]
name = "hdk_derive"
version = "0.0.100"
description = "Derive macros for the holochain HDK"
license-file = "LICENSE_CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "hdk" ]
categories = [ "cryptography" ]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = [ "full", "extra-traits" ] }
quote = "1"
proc-macro2 = "1"
paste = "=1.0.3"
holochain_zome_types = { path = "../holochain_zome_types" }
