[package]
name = "kitsune_p2p_direct_test"
version = "0.0.1"
description = "kitsune-p2p application demo separate crate integration tests"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
kitsune_p2p_direct = { version = "0.0.1", path = "../direct" }
observability = "0.1"
structopt = "0.3"
tokio = { version = "0.2", features = [ "full" ] }
